#!/bin/bash

# Get the Python file name from the environment variable
PYFILE=$PYFILE

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; 
   then
	echo "The PYFILE environment variable is not set."
	exit 1
   fi


# Compile the Python file
python3 -m py_compile -o my_main.pyc $PYFILE
echo "Compiling $PYFILE ..."

